name: CI

on: [push]

jobs:
  build:
    container:
        image: ballerina:latest
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: ballerina build *
    - name: Run a multi-line script
      run: ls -la
