name: CI

on: [push]

jobs:
  build:
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v1
    
      - name: Build
        uses: ballerina-platform/github-actions/cli/latest@master
        with:
          args: 
            build
             
   
       
  
