name: Ballerina example

on: [push]

jobs:
  build:
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v1
    
      - name: Ballerina Build
        uses: ballerina-platform/github-actions/cli/latest@master
        with:
          args: 
            build

      - name: Ballerina Push
        uses: ballerina-platform/github-actions/cli/latest@master
        with:
          env: 
            BALLERINA_CENTRAL_ACCESS_TOKEN = ${{ secrets.BallerinaCentralToken }}
          args: 
            push       
        
       
  
